---
# tasks file for aws-ec2
- name: launching AWS instance for configuring K8s-multi-node-cluster
  ec2:
      key_name: "{{ key }}"
      instance_type: "{{ instanceType }}"
      image: "{{ image_id }}"
      instance_tags: 
          Name: "{{item}}"
          Env: development
      region: "{{ region_name }}"
      group_id: "{{ security_group_results.group_id }}"
      vpc_subnet_id: "{{ subnet_result.subnet.id  }}"
      wait: yes
      count: 1
      assign_public_ip: yes
      aws_access_key: "{{ access_key }}"
      aws_secret_key: "{{ secret_key }}"
loop: "{{ Os_Names }}" 

- name: Refreshing inventory for new instances to come into the updated inventory
  meta: refresh_inventory
